### ISSUE TITLE
GDB cheatsheet

### ISSUE THREAD

**Issue by japaric** [rust-embedded/discovery#10]

**Comment by jamesmunns** [comment]
This might be a reasonable start: https://github.com/ferrous-systems/embedded-trainings/blob/master/beginner/docs/segment-1.md#part-4-debugging-code

**Comment by yusefkarim** [comment]
I have added a section to the appendix.

I am not an expert with GDB nor am I a concise writer. If you like these changes and see errors or things you would like added, please let me know!

**Comment by eldruin** [comment]
Added in #234
