### ISSUE TITLE
Explain how to return to 'rust' view in 'Debug It'

### ISSUE THREAD

**Issue by RandomInsano** [rust-embedded/discovery#127]
I'm playing around with `gdb` more than I never have (apparently I need to go off and learn that better) but I needed to be hit on the head that I get out of the `layout asm` view by going back to `layout src`. I'm fine opening a PR for this, just marking it down here.

https://rust-embedded.github.io/bookshelf/discovery/05-led-roulette/debug-it.html

**Comment by adamgreen** [comment]
I have attempted to address this issue with PR #141.

**Comment by adamgreig** [comment]
Thanks @adamgreen, I think that closes this issue.
