### ISSUE TITLE
Update discovery book website to track the latest changes to master.

### ISSUE THREAD

**Issue by Frederik-Baetens** [rust-embedded/discovery#128]
The source code at https://rust-embedded.github.io/discovery/05-led-roulette/the-led-and-delay-abstractions.html is not compatible with new versions of cortex-m-rt because newer cortex-m-rt uses the #[entry] tag instead of entry!(main).

Also, the Cargo.toml file (discovery/src/05-led-roulette/Cargo.toml) doesn't have cortex-m-rt in it leading to: ``error[E0463]: can't find crate for `cortex_m_rt` ``

However, the source code at https://github.com/rust-embedded/discovery/blob/master/src/05-led-roulette/the-led-and-delay-abstractions.md is already updated to work with #[entry] (and doesn't need cargo.toml changes), but the website doesn't seem to be updated with the latest code, i don't know why this is. 

So all of this would be fixed by just making the website track the master branch (which has up to date example code)

**Comment by japaric** [comment]
Thank you for the report.

It seems that the "update the build on each commit" logic broke after transferring this repository to the org but it has been fixed now.
