### ISSUE TITLE
Add link to bookshelf and FAQs to front page

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/discovery#129]
We should add links back to the main bookshelf (docs.rust-embedded.org) and to the [FAQ](https://rust-embedded.github.io/bookshelf/faq.html) to the front page of the embedonomicon.

**Comment by adamgreen** [comment]
I have attempted a fix in PR #140

**Comment by adamgreig** [comment]
Closed by #140, thanks @adamgreen!
