### ISSUE TITLE
Switch to recommending stable

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/discovery#139]
Now 1.30 is out, what stops anyone building all the examples with stable Rust?

**Comment by thejpster** [comment]
Ah, the answer is 2018 edition syntax.

**Comment by Kixunil** [comment]
So I figured it out. It's empty when compiling to `thumbv7em-none-eabi` and it works for `thumbv7em-none-eabihf`. I opened #147.

I believe that: "You can use stable Rust to develop for embedded" is much stronger message than "You don't have to type 5 lines saying `extern crate ...;`", so I'd suggest to make it stable.

**Comment by ricjac** [comment]
Is this one up for grabs?

**Comment by japaric** [comment]
This was done some time ago: https://rust-embedded.github.io/discovery/03-setup/index.html#rustc--cargo
