### ISSUE TITLE
L3GD20 datasheet link is broken

### ISSUE THREAD

**Issue by garfieldnate** [rust-embedded/discovery#170]
The documentation link for the L3GD20 given in 03-setup/index.html is broken:

![image](https://user-images.githubusercontent.com/778453/52525297-a3285200-2ca7-11e9-8a7c-141ddc71ef84.png)

**Comment by mathk** [comment]
Looks like the product is now retire. You can still found some copy on alldatasheet. @rust-embedded/resources  can this be upload to this repo?

**Comment by adamgreig** [comment]
Maybe [this](https://www.st.com/resource/en/datasheet/l3gd20h.pdf) datasheet is suitable instead? Not sure if anything relevant changes with the `H` version.

**Comment by mathk** [comment]
@adamgreig I have check but the I2c device addess is not the same.
