### ISSUE TITLE
Typo in 03-setup/verify.md: wrong permissions

### ISSUE THREAD

**Issue by foxpy** [rust-embedded/discovery#183]
Line 54 says:
```
As before, the permissions should be `crw-rw-r--`.
```
However, it should be:
```
As before, the permissions should be `crw-rw-rw-`.
```

**Comment by derekdreery** [comment]
Came here to add this issue. Interestingly, on my computer the permissions are `crw-rw-rw-+` - I don't know what the `+` means.

**Comment by foxpy** [comment]
> I don't know what the `+` means.

Well, maybe you have [ACL](https://wiki.archlinux.org/index.php/Access_Control_Lists) enabled on your machine.

**Comment by derekdreery** [comment]
Cool TIL that you can do role-based security on linux, and that @foxpy uses arch btw.
