### ISSUE TITLE
arm-none-eabi-gdb error

### ISSUE THREAD

**Issue by carriere4** [rust-embedded/discovery#203]
Getting this error message when I run `arm-none-eabi-gdb` to test the debugger for the first time:
```
“arm-none-eabi-gdb” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
```
to be clear - this is a popup alert delivered by MacOS

**Comment by jacobrosenthal** [comment]
Mac is becoming increasingly developer hostile. Any googling will show you
common possible fixes are using sudo, disabling SIP protection, and or
codesigning gdb.

**Comment by carriere4** [comment]
Wow! Thanks so much for the prompt reply. Will try those and if anything works, I'll report back. I've got a Linux machine, so I'll try that as well.

**Comment by carriere4** [comment]
works just fine on Linux, so will continue on that path. Will come back to this issue + open and update if I get a fix on the Mac side of things.
