### ISSUE TITLE
How do you open the GDB server?

### ISSUE THREAD

**Issue by David-OConnor** [rust-embedded/discovery#220]
[Relevant page](https://docs.rust-embedded.org/discovery/05-led-roulette/flash-it.html).

Description: *I mentioned that OpenOCD provides a GDB server so let's connect to that right now*
```bash
<gdb> -q target/thumbv7em-none-eabihf/debug/led-roulette
```

Unable to get this working on Windows. `gdb: the term gdb is not recognized as the name of a ...`. I've never seen the `<` as an opener to a terminal line. Perhaps a line is missing?

[This page](https://www.tincantools.com/gdb-debugger-with-openocd/) implies the command might be `arm-none-eabi-gdb -q target/thumbv7em-none-eabihf/debug/led-roulette`. This opens the `(gdb)` terminal with this warning: `(x86)\GNU Tools Arm Embedded\9 2019-q4-major\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.`. Subsequent steps appear to work.

**Comment by adamgreig** [comment]
On that page immediately below the line with `<gdb>` it says:

    NOTE: <gdb> represents a GDB program capable of debugging ARM binaries. This could be arm-none-eabi-gdb, gdb-multiarch or gdb depending on your system -- you may have to try all three.

You're supposed to substitute `<gdb>` with either `arm-none-eabi-gdb`, `gdb-multiarch`, or `gdb` as appropriate for your system.
