### ISSUE TITLE
07-registers - possibly wrong code example

### ISSUE THREAD

**Issue by ArcCha** [rust-embedded/discovery#229]
In section `Type safe manipulation` we have

```
    // Turn on the North LED
    gpioe.bsrr.write(|w| w.bs9().set_bit());

    // Turn on the East LED
    gpioe.bsrr.write(|w| w.bs11().set_bit());

    // Turn off the North LED
    gpioe.bsrr.write(|w| w.br9().set_bit());

    // Turn off the East LED
    gpioe.bsrr.write(|w| w.br11().set_bit());
```

I believe it should be

```
    // Turn on the North LED
    gpioe.bsrr.write(|w| w.bs9().set_bit());

    // Turn on the East LED
    gpioe.bsrr.write(|w| w.bs11().set_bit());

    // Turn off the North LED
    gpioe.bsrr.write(|w| w);

    // Turn off the East LED
    gpioe.bsrr.write(|w| w);
```

in order to actually turn the LEDs off as it is later mentioned in the book `If the identity closure (|w| w) is used, this method will set the register to its default (reset) value`.

**Comment by ArcCha** [comment]
Obviously not, my bad, did not read the example close enough when I attempted to modify it on my own. Sorry for the trouble and thanks for your awesome work!

**Comment by al-jshen** [comment]
Sorry to necro but I also came across the same "problem" so I thought I'd post. The register to turn off the LED is b**r**11 instead of b**s**11 (r instead of s).
