### ISSUE TITLE
USART - nothing is printing in minicom (i.e. X)

### ISSUE THREAD

**Issue by SuhailArshad1122** [rust-embedded/discovery#261]
Dear Sir,

I tried my best but, no out put show up in minicom, according to this coding (11-USART) X doesn't show up in minicom, please help I am stuck up.

Thanks, Regards
Suhail

**Comment by SuhailArshad1122** [comment]
Thanks I got it fixed

**Comment by fominok** [comment]
> Thanks I got it fixed

@SuhailArshad1122 can you please share how did you manage to do it? Do you use external serial adapter?

**Comment by faizsarwar** [comment]
> Thanks I got it fixed

how did you fixed that i am having same issue please help

**Comment by vortexofdoom** [comment]
For any future people who have this problem, I have gone through this twice (having forgotten it) and both times my issue was that I still had it set up for loopback, so disconnecting that worked.
