### ISSUE TITLE
linking with `rust-lld` failed: exit code:

### ISSUE THREAD

**Issue by Siraj454** [rust-embedded/discovery#290]
while making changes to led roulette building the code by command " cargo build --target thumbv7em-none-eabihf" it gives following errors "linking with `rust-lld` failed: exit code"

**Comment by adamgreig** [comment]
Hi, thanks for reporting an issue! Could you try running `cargo update` first? And after that, please could you give the full output when you run "cargo build --target thumbv7em-none-eabihf"? Everything that's printed, not just the final line.

**Comment by Siraj454** [comment]
it worked when I ran the build command first in discovery directory and
then on led-roulette, thanks for your quick response

**Comment by adamgreig** [comment]
Glad to hear it!
