### ISSUE TITLE
STM32F429Z Discovery STM32F429I-DISC1 with discovery guide

### ISSUE THREAD

**Issue by dkorzhevin** [rust-embedded/discovery#335]
Hello,

Is it possible to use STM32F429Z Discovery STM32F429I-DISC1 with https://docs.rust-embedded.org/discovery/ guide?

**Comment by therealprof** [comment]
Unfortunately not really. The generic parts do apply but the more detailed sections need some intricate adaptions.

**Comment by dkorzhevin** [comment]
Thank you, @therealprof

Then I will wait when STM32F3DISCOVERY  will be available in local store
