### ISSUE TITLE
parsing the itm.txt data

### ISSUE THREAD

**Issue by NitinSaxenait** [rust-embedded/discovery#399]
Hi, I am working with The Discovery Book and almost completed it. The task I am working on is to get the sensors readings from the itm.txt file and POST those readings on a server.
Now I am successfully able to get the readings from the sensor in the itm.txt but as told in the book the data is combined with the frames(Headers, payload). Now the problem is when I am taking this data from the itm.txt all unwanted data is coming with it.
And I am getting readings like this.

`"\u0003x = \u0001-\u000230\u00013\u0003 y =\u0001 \u000218\u00012\u0001 \u0002z \u0002= \u0001-\u000231\u00010\u0002 t\u0003heta\u0001 \u00012\u0001.\u00016\u000200\u000268\u00018\u0001",`

Whereas I want data to be in this form
```

x = -303 y = 182 z = -310 theta 2.600688
x = -297 y = 181 z = -312 theta 2.59427
```

How I can do that using the itm crate. I am stuck here and finding no way. I am expecting an answer to solve this. Thanks.

**Comment by sirhcel** [comment]
Hello @NitinSaxenait,

it looks like you are dealing with the [raw ITM data](https://github.com/rust-embedded/itm/blob/96d7710f2ba8f915668e95d67e0def961567c195/src/lib.rs#L72) sent from the target on the SWO pin. I assume that this data got dumped from the serial port directly into the `.txt` file. In this case the suffix `.txt` might be a red herring.

> How I can do that using the itm crate. I am stuck here and finding no way. 

You can extract the payload (you printed to ITM on the target) with a tool like [`itmdump`](https://github.com/rust-embedded/itm/blob/v0.3.1/src/bin/itmdump.rs) from the crate `itm`. When using your example data from above as `test.itm`
```
$ xxd test.itm
00000000: 0378 203d 2001 2d02 3330 0133 0320 7920  .x = .-.30.3. y
00000010: 3d01 2002 3138 0132 0120 027a 2002 3d20  =. .18.2. .z .=
00000020: 012d 0233 3101 3002 2074 0368 6574 6101  .-.31.0. t.heta.
00000030: 2001 3201 2e01 3602 3030 0236 3801 3801   .2...6.00.68.8.
```
this gives plain ASCII output (ignoring a warning on an unterminated ITM packet in this example data)
```
$ itmdump -f test.itm 2> /dev/null
x = -303 y = 182 z = -310 theta 2.600688
$ itmdump -f test.itm 2> /dev/null | xxd
00000000: 7820 3d20 2d33 3033 2079 203d 2031 3832  x = -303 y = 182
00000010: 207a 203d 202d 3331 3020 7468 6574 6120   z = -310 theta
00000020: 322e 3630 3036 3838                      2.600688
```

**Comment by NitinSaxenait** [comment]
@sirhcel thanks for the reply but I think you got the question wrong. I already got the readings without the raw ITM data on the itmdump console using this **itmdump -F -f itm.txt** as explained [here](https://docs.rust-embedded.org/discovery/06-hello-world/index.html). The thing is I am reading the itm.txt file directly using my code to get readings from there and from there only I am getting this unwanted data on my  **"server and terminal"**  On Server ->  `UnscaledMeasurement { x: 310, y: -71, z: -562` Reading the itm.txt file to get the readings. ```
pub fn notify() -> String {
    let (tx, rx) = channel();

    let mut watcher = watcher(tx, Duration::from_secs(10)).unwrap();

    watcher
        .watch("/tmp/itm.txt", RecursiveMode::NonRecursive)
        .unwrap();

    loop {
        match rx.recv() {
            Ok(event) => {
                let mut file = File::open("/tmp/itm.txt").expect("Error");
               /* let mut buffer = Vec::new();
                file.read_to_end(&mut buffer).expect("Error");
                let print = std::str::from_utf8(&buffer).unwrap();
                let t = print.replace(|c: char| !c.is_ascii(), "");
                println!("{}", print);
                return buffer;*/
                let mut buf_reader = BufReader::new(file);
                let c= buf_reader.lines().last().unwrap().expect("error");
                println!("{:?}",c);
                return c
            }
            Err(error) => println!("watch error: {:?}", error),
        }
    } 
```

**Comment by NitinSaxenait** [comment]
@sirhcel How I can read only the useful data from the itm.txt file in my code?

**Comment by eldruin** [comment]
You can use the [`itm`](https://github.com/rust-embedded/itm/blob/master/src/lib.rs) crate to decode the stream. See the code of [`itm-decode`](https://github.com/japaric/itm-tools/blob/master/src/bin/itm-decode.rs) for an example on how to use it.
