### ISSUE TITLE
[05-Rewrite] Led Roulette

### ISSUE THREAD

**Issue by caemor** [rust-embedded/discovery#401]
In chapter 5 the necessary target gets added: https://github.com/rust-embedded/discovery/blob/rewrite/src/05-led-roulette/build-it.md but it is already necessary to add the target for the verification of the installation in chapter 3.
Should I make a PR moving everything upto line 33 to the verification chapter (next to the cargo embed stuff from #400) or is it better to just move the rustup target over?

**Comment by hargoniX** [comment]
This was actually on my list of things to do after i got ch09 working and I was already planning on commenting under #400 that you could do both of that in one try. So yeah that would definitely be a good idea.
