### ISSUE TITLE
Can't flash led-roulette 

### ISSUE THREAD

**Issue by gravit22** [rust-embedded/discovery#440]
This is what I get when I try:
`    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `gdb-multiarch -q target/thumbv7em-none-eabihf/debug/led-roulette`
Reading symbols from target/thumbv7em-none-eabihf/debug/led-roulette...
(gdb) load
You can't do that when your target is `exec'
(gdb) 
`

**Comment by sirhcel** [comment]
For flashing a binary to the target, you need to connect to it beforehand. This is a bit [hidden in the documentation](https://docs.rust-embedded.org/discovery/f3discovery/05-led-roulette/flash-it.html#execute-gdb). Either 
```
(gdb) set target remote :3333
```
or passing this to GDB at startup as shown in the documentation.
