### ISSUE TITLE
"error: no such command: `embed`" from 03-setup/verify.html

### ISSUE THREAD

**Issue by jordanu** [rust-embedded/discovery#530]
It's entirely possible that I missed a step or misread instructions, but when I got to the command `cargo embed --target thumbv7em-none-eabihf` here is what happened:

```
jordan@jordan-TensorBook-late-2021:~/discovery/microbit/src/03-setup$ cargo embed --target thumbv7em-none-eabihf
error: no such command: `embed`

	View all installed commands with `cargo --list`
```

This was on a decently fresh install of Ubuntu 23.04.

I was able to resolve the problem by running the following two commands:
`sudo apt install -y pkg-config libusb-1.0-0-dev libftdi1-dev libudev-dev`
`cargo install cargo-embed`

**Comment by eldruin** [comment]
There is already guidance on how to do the setup [here](https://docs.rust-embedded.org/discovery/microbit/03-setup/index.html).
Closing.
