### ISSUE TITLE
Simple Chinese Tranlation

### ISSUE THREAD

**Issue by artwalker** [rust-embedded/discovery#549]
Hi, I want to translate the docs to the chinese version.
What should I do?
Thank you for helping me.

**Comment by eldruin** [comment]
Hi, there is already a simplified chinese translation by @jzow [here](https://jzow.github.io/discovery/). It is linked from the [main page](https://docs.rust-embedded.org/discovery/).

**Comment by Jzow** [comment]
Welcome, this is the address for the [Chinese manuscript](https://jzow.github.io/discovery/). If you have any questions about the proofreading documents, you can raise them and PR them for improvement

**Comment by artwalker** [comment]
@Jzow @eldruin Thanks a lot.

**Comment by eldruin** [comment]
Closing, then.
