### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by busslina** [rust-embedded/discovery#578]
URL: https://docs.rust-embedded.org/discovery/microbit/04-meet-your-hardware/terminology.html

Wrong: "However"
Correct: "How ever"

![imagen](https://github.com/rust-embedded/discovery/assets/73592852/d1eae631-e9fb-4333-a660-9a0baf3de3a9)

**Comment by BartMassey** [comment]
Thank for the careful read. The correct usage of "however" *vs* "how ever" is complicated. However, based on my research both "however you want'  and "how ever you want" are acceptable English, with the former preferred. Here's one link: https://ludwig.guru/s/however+you+want .

**Comment by busslina** [comment]
Cool, I'm spanish... Good to know and improve my level.

Good day
