### ISSUE TITLE
`itmdump` is hard to find

### ISSUE THREAD

**Issue by kper** [rust-embedded/discovery#61]
It was hard to find out that `itmdump` is hosted on `crates.io` and I have to install it with `cargo install itm`. You should definitely point that out more explicitly :)

**Comment by adamvoss** [comment]
Do you have a suggestion?

It is [mentioned in chapter 6 when you first need it](https://github.com/japaric/discovery/blame/master/src/06-hello-world/README.md#L62-L65) in case you missed the [installation instructions in chapter 3](https://japaric.github.io/discovery/03-setup/README.html#itmdump) (which I did).

**Comment by siobhanjacobson** [comment]
The details for installing `itmdump` are included now in the setup section: https://docs.rust-embedded.org/discovery/03-setup/index.html
