### ISSUE TITLE
gdb-arm-none-eabi removed from debian testing (buster) and newer

### ISSUE THREAD

**Issue by rmsthebest** [rust-embedded/discovery#91]
gdb-multiarch -q target/thumbv7em-none-eabihf/debug/led-roulette works though.

**Comment by johnthagen** [comment]
Confirmed that these instructions need to be updated for Ubuntu 18.04 and newer: https://rust-embedded.github.io/discovery/03-setup/linux.html

See: https://askubuntu.com/questions/1031103/how-to-install-gdb-arm-none-eabi-on-ubuntu-18-04
